[theme]
primaryColor="#FF7F00"
backgroundColor="#182136"
secondaryBackgroundColor="#2E3D63"
textColor="#EEEEEE"
font="sans serif"

[deprecation]
showPyplotGlobalUse = false

[server]
maxUploadSize = 2000
maxMessageSize = 8000

[browser]
gatherUsageStats = false